version: '2'
services:
  slapd:
    build: .
    ports:
      - "389:389"
      - "636:636"
    volumes:
      - type: bind
        source: ./etc/ldap/SITE-slapd.conf
        target: /etc/ldap/SITE-slapd.conf
      - type: bind
        source: ./etc/ldap/SITE-schema/
        target: /etc/ldap/SITE-schema/
    container_name: slapd-consumer
    restart: always
    logging:
      driver: syslog
      options:
        syslog-facility: "local7"
